### ISSUE TITLE
High cpu usage and occasionall unavailability of metrics port

### ISSUE THREAD

**Issue by rlex** [sstarcher/helm-exporter#73]
Hello! have an issue with helm-exporter.
I see pretty high (30-50% of single core, sometimes more) of typical CPU usage.
In addition, sometimes target becomes unavailable in prometheus (timeout).
Wondering what can cause it?
Maybe 30s polling interval (helm-exporter does periodic polling, or does it query repos on every /metrics call? I have a fair amount of repos to check)

**Comment by sstarcher** [comment]
It will do it on each call to `/metrics` you can set it up to do this in the background and to cache the results if you use https://github.com/sstarcher/helm-exporter/blob/master/main.go#L50

**Comment by rlex** [comment]
Thanks! I guess default prometheus scraping of 30s sometimes broke helm-exporter.
Much better now, might be worth better documenting that in helm chart? https://github.com/sstarcher/helm-exporter/blob/master/helm/values.yaml#L6

**Comment by sstarcher** [comment]
It could certainly help people who have large clusters

**Comment by evgeny-test** [comment]
Hello!
I am having a similar problem.
My cluster has no Internet access.
I have set a variable "latestChartVersion: false", but have a long startup time and CrashLooping.

I tried setting a variable "initialDelaySeconds: 120" for reading and liveness probes, than I can see in logs
time="2021-12-10T16:06:27Z" level=warning msg="failed to update artifacthub cache due to Get \"https://artifacthub.io/api/v1/helm-exporter\": dial tcp 13.33.240.37:443: i/o timeout "

Is there a standard way to disable artifacthub update?

**Comment by sstarcher** [comment]
Your error is not the same thing.  Your issue is it trying to fetch charts, but you have no internet access.  I believe currently for it to work you would need to specify OverrideRegistries for each of your charts.  If you do that it will not fall back to artifacthub.

Certainly a bug that it should not cause a crashback loop if it can't reach artifacthub

**Comment by evgeny-test** [comment]
Thanks for the quick response!

I have set the following settings, but I still get an unavailable artifacthub. 
I don't have a real local helm repository with this charts. 

```
helm-exporter:
...
  config:
    helmRegistries:
      override:
        - registry:
            url: "localhost"
          charts:
            - es
            - kibana
            - logstash
            - prometheus
            - ...

```

Why use artifacthub if I disabled latestChartVersion?

For info: When I set the setting "initialDelaySeconds: 120", the pod works fine, despite the warning.

**Comment by sstarcher** [comment]
I bet the issue is it's failing in init where we do the cache.  
https://github.com/sstarcher/helm-exporter/blob/67c0a2e42bb9625f4bbb4234a3f7eb1f5ee1b68e/registries/helm_hub.go#L60

So `latest chart version` is disabling the actual fetching, but we are still polling the cache.  We likely need a way to disable the cache from happening or move it to a separate function call.  I would consider that a bug.
