### ISSUE TITLE
Expose newer version of chart

### ISSUE THREAD

**Issue by estahn** [sstarcher/helm-exporter#8]
With helm whatsup we get the latest version of a chart. Would be nice to have this as metric and possibly alert on when a newer version is available

**Comment by sstarcher** [comment]
Interesting idea would this be a separate metric or are you thinking of a label.  Doing it via a label may increase the cardinality more than we want.  Or are you thinking of just a boolean of an update exists?

**Comment by sstarcher** [comment]
If we just wanted to know if an update existed we could do 
`helm_chart_update_available{release="XXX"} 1`

If the ask is specifically for the version we are updating to that's a different beast.

**Comment by estahn** [comment]
@sstarcher I think boolean is enough, e.g. `helm_chart_latest{release="XXX"} 1`. This would allow alerts on whether the currently installed chart is different from the one in the repository.

Example:
```
helm_chart_info{chart="ark",release="ark",version="1.2.1"}
helm_chart_latest{chart="ark",release="ark",version="1.2.2"}
```

**Comment by mkjoerg** [comment]
@estahn Maybe alerting on each minor version could produce a lot of noise on the alerting systems. 
I think adding additionally the label version_newest containing the most recent version would be great to do alerts based on semantic versioning and would allow much more customization. Due to the fact that the newest version is already provided by the helm plugin, this information should be cheap to retrieve.

So maybe this 
```
helm_chart_info{chart="ark",release="ark",version="1.2.1", version_newest="1.2.10", update_available="1"}
```
Could provide a lot more benefits to the monitoring system, because users could use regex and alert only for major updates if they wish, but would still be able to consume the update boolean?
What do you think?

**Comment by sstarcher** [comment]
I would lean toward making it a separate metric to limit the cardinality and allow it to be joined with the helm_chart_info metric.

**Comment by mkjoerg** [comment]
Yeah that would be a better option maybe, because it is actually a separate domain and could come in a different timeframe.

**Comment by bstrdsmkr** [comment]
Any update on this?

I need a grafana dashboard that shows a table panel listing which charts have newer versions available so our maintenance team can start looking into updating.

Similarly, I need to set a Prometheus alert to notify the team when a chart becomes outdated

**Comment by sstarcher** [comment]
@bstrdsmkr as of June we have the latestVersion label defined for the helm_chart_info.  You should be able to leverage that
https://github.com/sstarcher/helm-exporter/commit/4e8d4fc1ab300d199008a24a2332448cfd42372f

**Comment by sstarcher** [comment]
I'm going to close this as we now have `latestVersion` please file a ticket if that is not sufficient for your goal.
